export const UNIVERSITIES_NI = [
    "Universidad Centroamericana (UCA)",
    "Universidad Nacional Autónoma de Nicaragua (UNAN-Managua)",
    "UNAN-León",
    "Universidad Nacional de Ingeniería (UNI)",
    "Universidad Americana (UAM)", 
    "Universidad Politécnica de Nicaragua (UPOLI)",
    "Universidad Católica Redemptoris Mater (UNICA)",
    "Universidad Tecnológica La Salle (ULSA)",
    "Universidad de Ciencias Comerciales (UCC)",
    "Universidad Paulo Freire (UPF)",
    "Universidad Nicaragüense de Ciencia y Tecnología (UCYT)",
    "Universidad Martín Lutero (UML)",
    "Universidad Evangélica Nicaragüense (UENIC-MLK)",
    "Universidad Internacional Antonio de Valdivieso (UNIAV)",
    "Bluefields Indian & Caribbean University (BICU)",
    "Universidad de las Regiones Autónomas de la Costa Caribe Nicaragüense (URACCAN)",
    "Universidad Iberoamericana de Ciencia y Tecnologia",
];
